### PR TITLE
Fix for some super minor typos

### PR DESCRIPTION
**Pull request by josephjacks**

### CODE REVIEW

**Comment by aboodman** [comment]
Thank you @josephjacks - really appreciate it. If you are OK with assigning your copyright on these massive changes to us, please fill out https://github.com/rocicorp/replicache/blob/main/contributing.md#legal and I will land this.

Otherwise I will ponder your suggestion and fix in my own way 😆.

**Comment by josephjacks** [comment]
> Thank you @josephjacks - really appreciate it. If you are OK with assigning your copyright on these massive changes to us, please fill out https://github.com/rocicorp/replicache/blob/main/contributing.md#legal and I will land this.
> 
> 
> 
> Otherwise I will ponder your suggestion and fix in my own way 😆.

Done

**Comment by aboodman** [comment]
@arv we have to turn off the perf bot until it's stabilized, it's so irritating (and looks bad too :)).

**Comment by arv** [comment]
> @arv we have to turn off the perf bot until it's stabilized, it's so irritating (and looks bad too :)).

Turned it off for now.

The vercel peeps said that there is no way to not have a Preview on a PR... I could change how the Preview works so that it does nothing on the PR but that is for another day

**Pull request merged**
